services:
  pyfractal:
    build:
      context: .
      dockerfile: pyfractal.dockerfile
    environment:
      - PROGRAM_NAME=main
      - DATA_DIR=/app/data
      - DATASET=protein_ligands.txt
    volumes:
      - .:/app
    command: python src/compress/metadata.py >> /app/logs/metadata.log 2>&1
