services:
  pyfractal:
    build:
      context: .
      dockerfile: pyfractal.dockerfile
    environment:
      - PROGRAM_NAME=main
      - DATA_DIR=/app/data
      - DATASET=nicleic_rna.txt
    volumes:
      - .:/app
    # command: sh run_metadata_with_different_datasets.sh
    command: /usr/bin/time -v python src/compress/metadata.py
